=== kamal-F/Q1W2E32C/quiz.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="barangkriminal">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="deskripsi"/>
                <xs:element ref="harga"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:pattern
    				value="([A-Z]{2}-[0-9]{4}-[A-Z]{2})">
    			</xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="deskripsi" type="xs:string"/>
    <xs:element name="harga" type="xs:double"/>
</xs:schema>

=== kamal-F/Q1W2E32C/quiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<barangkriminal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quiz.xsd">
	<barang>
		<kode>QS-9345-SW</kode>
		<deskripsi>Windows 10 full crack</deskripsi>
		<harga>5000.500</harga>
	</barang>
	<barang>
		<kode>AA-1234-GG</kode>
		<deskripsi>Windows 8 full crack</deskripsi>
		<harga>5000</harga>
	</barang>
	<barang>
		<kode>AA-7890-GG</kode>
		<deskripsi>Ms Office full crack</deskripsi>
		<harga>2250.500</harga>
	</barang>
</barangkriminal>
